### ISSUE TITLE
Accessing content without Javascript?

### ISSUE THREAD

**Issue by paulcmal** [timgrossmann/stateOfVeganism#1]
Hi,

I'd like to use your website but unfortunately it doesn't work without client-side Javascript enabled. I just don't understand the use of it to present a few articles without interaction (from what i gathered) : HTML/CSS work just fine for that, is more accessible (when written properly), more lightweight on resources for your clients and your server, and doesn't require loading as much junk over the network.

Here's one of many presentations on the topic : [Dear dev, the web isn't about you](https://sonniesedge.co.uk/talks/dear-developer)

Have a good day :)

**Comment by timgrossmann** [comment]
@paulcmal Sorry I never answered the issue, I've somehow never looked into the issues here...

You are absolutely right!
I've added the article to my reading list and will take it into consideration in my next project.

Thank you
