### ISSUE TITLE
Icon missing in Firefox

### ISSUE THREAD

**Issue by mathiasnovas** [timgrossmann/stateOfVeganism#2]
First of all: Well done on the project. It's going to be very interesting to follow. ✨🌱

I'm really uncertain as to why this is happening, but in my Firefox, the V-icon is replaced with a bogus character. The `.svg` loads fine when previewing it in the inspector.

**What it looks like in Firefox**
![Firefox screenshot](https://i.imgur.com/ut7zuOk.png)

**Firefox version info**
![Firefox version info screenshot](https://i.imgur.com/qzgJ4R1.png)

Also I am on macOS High Sierra 10.13.6.

**Comment by timgrossmann** [comment]
@mathiasnovas Sorry I never answered the issue, I've somehow never looked into the issues here...
