### ISSUE TITLE
Die angeforderte Adresse konnte nicht aufgelöst werden 

### ISSUE THREAD

**Issue by koehlertimo** [timgrossmann/stateOfVeganism#3]
Wenn ich auf den Link in der Readme klicke dann kommt folgende Fehler Meldung:

"Die angeforderte Adresse konnte nicht aufgelöst werden "

**Comment by timgrossmann** [comment]
@koehlertimo Hi Timo, sorry, das Projekt habe ich schon seit einiger Zeit nicht mehr online. Komischerweise leider auch nie die Issues und Vorschläge der anderen beiden angeschaut...

Das Projekt entstand im Rahmen einer Vorlesung entstanden und leider habe ich es danach nicht mehr weiter verfolgt.
Zugegebenermaßen sehr schade, da sich die Berichterstattung, zumindest gefühlt, wirklich sehr verbessert hat 😄
